server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes: ## 路由规则
    film-service:  ## application.name -> 服务名称
      path: /film-api/**  # 匹配规则
    cinema-service:
      path: /cinema-api/**

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 10