server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
zuul:
  prefix: "/meetingfilm/"
  routes:
    meetingfilm-user:
      path: /userapi/**
      serviceId: user-service
      retryable: true   # 是否允许重试，饿汉模式
    meetingfilm-cinema:
      path: /cinemaapi/**
      serviceId: cinema-service
      retryable: true
    meetingfilm-film:
      path: /filmapi/**
      serviceId: film-service
      retryable: true
    meetingfilm-hall:
      path: /hallapi/**
      serviceId: hall-service
      retryable: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enable: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000